### PR TITLE
Add home page

### PR DESCRIPTION
**Pull request by joshuarmil**

### CODE REVIEW

**Comment by joshuarmil** [comment]
@ptravers Cool, removed the title, does that mean I should clear out <head> or is that fine?

**Comment by ptravers** [comment]
LGTM = Looks Good To Merge!

**Comment by ptravers** [comment]
Nice work!

**Comment by joshuarmil** [comment]
@ptravers Also, should I delete the branch now?

**Comment by joshuarmil** [comment]
Oop, what I saw "clear out", I meant, should i clear out head since it wasn't in the test?

**Comment by ptravers** [comment]
Head is okay I think. I don't know how to test this properties. You can but
it's also okay to leave it up

**Pull request merged**
